const LIGHT_ASSET = { WIDTH: 1387, HEIGHT: 576 };

const VISIBLE_AREA = {
  CENTER_X: LIGHT_ASSET.WIDTH / 2,
  CENTER_Y: LIGHT_ASSET.HEIGHT / 2,
  RADIUS: 180,
};

const LIGHT_MARGIN_RATIO = 0.02;

const LIGHT_RADIUS_WORLD = {
  MAX: 120,
  MIN: 30,
  RESPONSE_SPEED: 10,
};

export { LIGHT_ASSET, VISIBLE_AREA, LIGHT_MARGIN_RATIO, LIGHT_RADIUS_WORLD };
