const DEFAULT_LIMIT = 60;

const MILLISECONDS_PER_SECOND = 1000;

const LOADING_TIME = {
  MIN_VISIBLE_MS: 1500,
  TIP_CYCLE_MS: 1500,
  BG_SCROLL_DURATION_MS: 12000,
};

export { DEFAULT_LIMIT, MILLISECONDS_PER_SECOND, LOADING_TIME };
